services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  watch_socket_server:
    build: 
      context: 
        watch_socket_server
    ports:
      - "2222:2222"
    volumes:
      - ./watch_socket_server/app:/app
    command: >
        sh -c "python watch_socket_server.py"
    stop_signal: SIGINT

  webrtc_od_detect_server:
    build: 
      context: webrtc_od_detect_server
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./webrtc_od_detect_server/src:/src
    command: >
      sh -c "python server_test.py"

  fastapi_server:
    build:
      context: fastapi_server
    ports:
      - "80:80"
    volumes:
      - ./fastapi_server/app:/app
    #   sh -c "python watch_socket_test.py"
